# Premier League Standings Project

### This is for testing purpose

In [64]:
import pandas as pd
import os
import json
import requests
from mysql import connector
from dotenv import load_dotenv

In [69]:
# Calling the load_dotenv() function
load_dotenv()

True

In [70]:
## I have updated API_HOST and API_KEY in .env file, as I want to use different API 
## Since I am getting old value of API_HOST and API_KEY from .env file, therefore I am forcing override of dotenv


load_dotenv(override=True)

True

In [5]:
API_KEY = os.getenv("API_KEY")
API_HOST = os.getenv("API_HOST")
SEASON = 2024
LEAGUE_ID = 47

In [6]:
url = "https://eplcurrentstandings.p.rapidapi.com/"

headers = {
	"x-rapidapi-key": API_KEY,
	"x-rapidapi-host": API_HOST,
	"Content-Type": "application/json"
}

## ------------------------------Extracting Data from API-------------------------

In [9]:
response = requests.get(url, headers=headers)
print(response)

<Response [200]>

In [10]:
print("Status Code:", response.status_code)
print("Content-Type:", response.headers.get("Content-Type"))
print("Response Text:")
print(response.text)

Status Code: 200
Content-Type: application/json
Response Text:
 { "rankings" : [{"team_rank": "1", "team_name": "Liverpool", "games_played": "23", "won": "15", "tied": "6", "lost": "2", "goals_scored": "52", "goals_against": "22"}, {"team_rank": "2", "team_name": "Manchester City", "games_played": "22", "won": "15", "tied": "4", "lost": "3", "goals_scored": "54", "goals_against": "25"}, {"team_rank": "3", "team_name": "Arsenal", "games_played": "23", "won": "15", "tied": "4", "lost": "4", "goals_scored": "47", "goals_against": "22"}, {"team_rank": "4", "team_name": "Aston Villa", "games_played": "23", "won": "14", "tied": "4", "lost": "5", "goals_scored": "49", "goals_against": "30"}, {"team_rank": "5", "team_name": "Tottenham Hotspur", "games_played": "23", "won": "13", "tied": "5", "lost": "5", "goals_scored": "49", "goals_against": "35"}, {"team_rank": "6", "team_name": "Manchester United", "games_played": "23", "won": "12", "tied": "2", "lost": "9", "goals_scored": "31", "goals_against": "32"}, {"team_rank": "7", "team_name": "West Ham United", "games_played": "23", "won": "10", "tied": "6", "lost": "7", "goals_scored": "36", "goals_against": "36"}, {"team_rank": "8", "team_name": "Brighton and Hove Albion", "games_played": "23", "won": "9", "tied": "8", "lost": "6", "goals_scored": "42", "goals_against": "38"}, {"team_rank": "9", "team_name": "Newcastle United", "games_played": "23", "won": "10", "tied": "3", "lost": "10", "goals_scored": "48", "goals_against": "37"}, {"team_rank": "10", "team_name": "Wolverhampton Wanderers", "games_played": "23", "won": "9", "tied": "5", "lost": "9", "goals_scored": "37", "goals_against": "37"}, {"team_rank": "11", "team_name": "Chelsea", "games_played": "23", "won": "9", "tied": "4", "lost": "10", "goals_scored": "38", "goals_against": "39"}, {"team_rank": "12", "team_name": "Bournemouth", "games_played": "22", "won": "7", "tied": "6", "lost": "9", "goals_scored": "30", "goals_against": "41"}, {"team_rank": "13", "team_name": "Fulham", "games_played": "23", "won": "7", "tied": "5", "lost": "11", "goals_scored": "30", "goals_against": "38"}, {"team_rank": "14", "team_name": "Crystal Palace", "games_played": "23", "won": "6", "tied": "6", "lost": "11", "goals_scored": "26", "goals_against": "40"}, {"team_rank": "15", "team_name": "Brentford", "games_played": "22", "won": "6", "tied": "4", "lost": "12", "goals_scored": "32", "goals_against": "39"}, {"team_rank": "16", "team_name": "Nottingham Forest", "games_played": "23", "won": "5", "tied": "6", "lost": "12", "goals_scored": "28", "goals_against": "41"}, {"team_rank": "17", "team_name": "Luton Town", "games_played": "22", "won": "5", "tied": "5", "lost": "12", "goals_scored": "32", "goals_against": "42"}, {"team_rank": "18", "team_name": "Everton *", "games_played": "23", "won": "8", "tied": "5", "lost": "10", "goals_scored": "26", "goals_against": "30"}, {"team_rank": "19", "team_name": "Burnley", "games_played": "23", "won": "3", "tied": "4", "lost": "16", "goals_scored": "24", "goals_against": "47"}, {"team_rank": "20", "team_name": "Sheffield United", "games_played": "23", "won": "2", "tied": "4", "lost": "17", "goals_scored": "19", "goals_against": "59"}] }

In [11]:
payload = response.json()

## Printing the response which we are getting from API
print(payload)

{'rankings': [{'team_rank': '1', 'team_name': 'Liverpool', 'games_played': '23', 'won': '15', 'tied': '6', 'lost': '2', 'goals_scored': '52', 'goals_against': '22'}, {'team_rank': '2', 'team_name': 'Manchester City', 'games_played': '22', 'won': '15', 'tied': '4', 'lost': '3', 'goals_scored': '54', 'goals_against': '25'}, {'team_rank': '3', 'team_name': 'Arsenal', 'games_played': '23', 'won': '15', 'tied': '4', 'lost': '4', 'goals_scored': '47', 'goals_against': '22'}, {'team_rank': '4', 'team_name': 'Aston Villa', 'games_played': '23', 'won': '14', 'tied': '4', 'lost': '5', 'goals_scored': '49', 'goals_against': '30'}, {'team_rank': '5', 'team_name': 'Tottenham Hotspur', 'games_played': '23', 'won': '13', 'tied': '5', 'lost': '5', 'goals_scored': '49', 'goals_against': '35'}, {'team_rank': '6', 'team_name': 'Manchester United', 'games_played': '23', 'won': '12', 'tied': '2', 'lost': '9', 'goals_scored': '31', 'goals_against': '32'}, {'team_rank': '7', 'team_name': 'West Ham United', 'games_played': '23', 'won': '10', 'tied': '6', 'lost': '7', 'goals_scored': '36', 'goals_against': '36'}, {'team_rank': '8', 'team_name': 'Brighton and Hove Albion', 'games_played': '23', 'won': '9', 'tied': '8', 'lost': '6', 'goals_scored': '42', 'goals_against': '38'}, {'team_rank': '9', 'team_name': 'Newcastle United', 'games_played': '23', 'won': '10', 'tied': '3', 'lost': '10', 'goals_scored': '48', 'goals_against': '37'}, {'team_rank': '10', 'team_name': 'Wolverhampton Wanderers', 'games_played': '23', 'won': '9', 'tied': '5', 'lost': '9', 'goals_scored': '37', 'goals_against': '37'}, {'team_rank': '11', 'team_name': 'Chelsea', 'games_played': '23', 'won': '9', 'tied': '4', 'lost': '10', 'goals_scored': '38', 'goals_against': '39'}, {'team_rank': '12', 'team_name': 'Bournemouth', 'games_played': '22', 'won': '7', 'tied': '6', 'lost': '9', 'goals_scored': '30', 'goals_against': '41'}, {'team_rank': '13', 'team_name': 'Fulham', 'games_played': '23', 'won': '7', 'tied': '5', 'lost': '11', 'goals_scored': '30', 'goals_against': '38'}, {'team_rank': '14', 'team_name': 'Crystal Palace', 'games_played': '23', 'won': '6', 'tied': '6', 'lost': '11', 'goals_scored': '26', 'goals_against': '40'}, {'team_rank': '15', 'team_name': 'Brentford', 'games_played': '22', 'won': '6', 'tied': '4', 'lost': '12', 'goals_scored': '32', 'goals_against': '39'}, {'team_rank': '16', 'team_name': 'Nottingham Forest', 'games_played': '23', 'won': '5', 'tied': '6', 'lost': '12', 'goals_scored': '28', 'goals_against': '41'}, {'team_rank': '17', 'team_name': 'Luton Town', 'games_played': '22', 'won': '5', 'tied': '5', 'lost': '12', 'goals_scored': '32', 'goals_against': '42'}, {'team_rank': '18', 'team_name': 'Everton *', 'games_played': '23', 'won': '8', 'tied': '5', 'lost': '10', 'goals_scored': '26', 'goals_against': '30'}, {'team_rank': '19', 'team_name': 'Burnley', 'games_played': '23', 'won': '3', 'tied': '4', 'lost': '16', 'goals_scored': '24', 'goals_against': '47'}, {'team_rank': '20', 'team_name': 'Sheffield United', 'games_played': '23', 'won': '2', 'tied': '4', 'lost': '17', 'goals_scored': '19', 'goals_against': '59'}]}

## ------------------------------Transforming Data----------------------------

In [34]:
formatted_response = json.dumps(payload, indent=4)
print(formatted_response)

{
    "rankings": [
        {
            "team_rank": "1",
            "team_name": "Liverpool",
            "games_played": "23",
            "won": "15",
            "tied": "6",
            "lost": "2",
            "goals_scored": "52",
            "goals_against": "22"
        },
        {
            "team_rank": "2",
            "team_name": "Manchester City",
            "games_played": "22",
            "won": "15",
            "tied": "4",
            "lost": "3",
            "goals_scored": "54",
            "goals_against": "25"
        },
        {
            "team_rank": "3",
            "team_name": "Arsenal",
            "games_played": "23",
            "won": "15",
            "tied": "4",
            "lost": "4",
            "goals_scored": "47",
            "goals_against": "22"
        },
        {
            "team_rank": "4",
            "team_name": "Aston Villa",
            "games_played": "23",
            "won": "14",
            "tied": "4",
            "lost": "5",
            "goals_scored": "49",
            "goals_against": "30"
        },
        {
            "team_rank": "5",
            "team_name": "Tottenham Hotspur",
            "games_played": "23",
            "won": "13",
            "tied": "5",
            "lost": "5",
            "goals_scored": "49",
            "goals_against": "35"
        },
        {
            "team_rank": "6",
            "team_name": "Manchester United",
            "games_played": "23",
            "won": "12",
            "tied": "2",
            "lost": "9",
            "goals_scored": "31",
            "goals_against": "32"
        },
        {
            "team_rank": "7",
            "team_name": "West Ham United",
            "games_played": "23",
            "won": "10",
            "tied": "6",
            "lost": "7",
            "goals_scored": "36",
            "goals_against": "36"
        },
        {
            "team_rank": "8",
            "team_name": "Brighton and Hove Albion",
            "games_played": "23",
            "won": "9",
            "tied": "8",
            "lost": "6",
            "goals_scored": "42",
            "goals_against": "38"
        },
        {
            "team_rank": "9",
            "team_name": "Newcastle United",
            "games_played": "23",
            "won": "10",
            "tied": "3",
            "lost": "10",
            "goals_scored": "48",
            "goals_against": "37"
        },
        {
            "team_rank": "10",
            "team_name": "Wolverhampton Wanderers",
            "games_played": "23",
            "won": "9",
            "tied": "5",
            "lost": "9",
            "goals_scored": "37",
            "goals_against": "37"
        },
        {
            "team_rank": "11",
            "team_name": "Chelsea",
            "games_played": "23",
            "won": "9",
            "tied": "4",
            "lost": "10",
            "goals_scored": "38",
            "goals_against": "39"
        },
        {
            "team_rank": "12",
            "team_name": "Bournemouth",
            "games_played": "22",
            "won": "7",
            "tied": "6",
            "lost": "9",
            "goals_scored": "30",
            "goals_against": "41"
        },
        {
            "team_rank": "13",
            "team_name": "Fulham",
            "games_played": "23",
            "won": "7",
            "tied": "5",
            "lost": "11",
            "goals_scored": "30",
            "goals_against": "38"
        },
        {
            "team_rank": "14",
            "team_name": "Crystal Palace",
            "games_played": "23",
            "won": "6",
            "tied": "6",
            "lost": "11",
            "goals_scored": "26",
            "goals_against": "40"
        },
        {
            "team_rank": "15",
            "team_name": "Brentford",
            "games_played": "22",
            "won": "6",
            "tied": "4",
            "lost": "12",
            "goals_scored": "32",
            "goals_against": "39"
        },
        {
            "team_rank": "16",
            "team_name": "Nottingham Forest",
            "games_played": "23",
            "won": "5",
            "tied": "6",
            "lost": "12",
            "goals_scored": "28",
            "goals_against": "41"
        },
        {
            "team_rank": "17",
            "team_name": "Luton Town",
            "games_played": "22",
            "won": "5",
            "tied": "5",
            "lost": "12",
            "goals_scored": "32",
            "goals_against": "42"
        },
        {
            "team_rank": "18",
            "team_name": "Everton *",
            "games_played": "23",
            "won": "8",
            "tied": "5",
            "lost": "10",
            "goals_scored": "26",
            "goals_against": "30"
        },
        {
            "team_rank": "19",
            "team_name": "Burnley",
            "games_played": "23",
            "won": "3",
            "tied": "4",
            "lost": "16",
            "goals_scored": "24",
            "goals_against": "47"
        },
        {
            "team_rank": "20",
            "team_name": "Sheffield United",
            "games_played": "23",
            "won": "2",
            "tied": "4",
            "lost": "17",
            "goals_scored": "19",
            "goals_against": "59"
        }
    ]
}

In [35]:
standings_list = payload['rankings']
standings_list

[{'team_rank': '1',
  'team_name': 'Liverpool',
  'games_played': '23',
  'won': '15',
  'tied': '6',
  'lost': '2',
  'goals_scored': '52',
  'goals_against': '22'},
 {'team_rank': '2',
  'team_name': 'Manchester City',
  'games_played': '22',
  'won': '15',
  'tied': '4',
  'lost': '3',
  'goals_scored': '54',
  'goals_against': '25'},
 {'team_rank': '3',
  'team_name': 'Arsenal',
  'games_played': '23',
  'won': '15',
  'tied': '4',
  'lost': '4',
  'goals_scored': '47',
  'goals_against': '22'},
 {'team_rank': '4',
  'team_name': 'Aston Villa',
  'games_played': '23',
  'won': '14',
  'tied': '4',
  'lost': '5',
  'goals_scored': '49',
  'goals_against': '30'},
 {'team_rank': '5',
  'team_name': 'Tottenham Hotspur',
  'games_played': '23',
  'won': '13',
  'tied': '5',
  'lost': '5',
  'goals_scored': '49',
  'goals_against': '35'},
 {'team_rank': '6',
  'team_name': 'Manchester United',
  'games_played': '23',
  'won': '12',
  'tied': '2',
  'lost': '9',
  'goals_scored': '31',
  'goals_against': '32'},
 {'team_rank': '7',
  'team_name': 'West Ham United',
  'games_played': '23',
  'won': '10',
  'tied': '6',
  'lost': '7',
  'goals_scored': '36',
  'goals_against': '36'},
 {'team_rank': '8',
  'team_name': 'Brighton and Hove Albion',
  'games_played': '23',
  'won': '9',
  'tied': '8',
  'lost': '6',
  'goals_scored': '42',
  'goals_against': '38'},
 {'team_rank': '9',
  'team_name': 'Newcastle United',
  'games_played': '23',
  'won': '10',
  'tied': '3',
  'lost': '10',
  'goals_scored': '48',
  'goals_against': '37'},
 {'team_rank': '10',
  'team_name': 'Wolverhampton Wanderers',
  'games_played': '23',
  'won': '9',
  'tied': '5',
  'lost': '9',
  'goals_scored': '37',
  'goals_against': '37'},
 {'team_rank': '11',
  'team_name': 'Chelsea',
  'games_played': '23',
  'won': '9',
  'tied': '4',
  'lost': '10',
  'goals_scored': '38',
  'goals_against': '39'},
 {'team_rank': '12',
  'team_name': 'Bournemouth',
  'games_played': '22',
  'won': '7',
  'tied': '6',
  'lost': '9',
  'goals_scored': '30',
  'goals_against': '41'},
 {'team_rank': '13',
  'team_name': 'Fulham',
  'games_played': '23',
  'won': '7',
  'tied': '5',
  'lost': '11',
  'goals_scored': '30',
  'goals_against': '38'},
 {'team_rank': '14',
  'team_name': 'Crystal Palace',
  'games_played': '23',
  'won': '6',
  'tied': '6',
  'lost': '11',
  'goals_scored': '26',
  'goals_against': '40'},
 {'team_rank': '15',
  'team_name': 'Brentford',
  'games_played': '22',
  'won': '6',
  'tied': '4',
  'lost': '12',
  'goals_scored': '32',
  'goals_against': '39'},
 {'team_rank': '16',
  'team_name': 'Nottingham Forest',
  'games_played': '23',
  'won': '5',
  'tied': '6',
  'lost': '12',
  'goals_scored': '28',
  'goals_against': '41'},
 {'team_rank': '17',
  'team_name': 'Luton Town',
  'games_played': '22',
  'won': '5',
  'tied': '5',
  'lost': '12',
  'goals_scored': '32',
  'goals_against': '42'},
 {'team_rank': '18',
  'team_name': 'Everton *',
  'games_played': '23',
  'won': '8',
  'tied': '5',
  'lost': '10',
  'goals_scored': '26',
  'goals_against': '30'},
 {'team_rank': '19',
  'team_name': 'Burnley',
  'games_played': '23',
  'won': '3',
  'tied': '4',
  'lost': '16',
  'goals_scored': '24',
  'goals_against': '47'},
 {'team_rank': '20',
  'team_name': 'Sheffield United',
  'games_played': '23',
  'won': '2',
  'tied': '4',
  'lost': '17',
  'goals_scored': '19',
  'goals_against': '59'}]

In [ ]:
# Formatting the standings list for better understanding
formatted_standings_list = json.dumps(standings_list, indent=4)
print(formatted_standings_list)

In [37]:
## Points for each team in Premier League are calculated as follows -
## 3 points for a win, 1 point for a draw, and 0 points for a loss.

Manchester_City_Games_Won = int(standings_list[0]['won'])
Manchester_City_Games_Drawn = int(standings_list[0]['tied'])

Manchester_City_Points = (Manchester_City_Games_Won * 3) + (Manchester_City_Games_Drawn * 1)

print(Manchester_City_Points)

51

In [82]:
## Setting up rows and columns for dataframe to store data in clean table like format 
rows = []
column_names = ['season', 'position', 'team', 'played', 'won', 'draw', 'lost', 'goals_for', 'goals_against', 'goals_diff', 'points']

## Looping through all the teams in standings list to create the dataframe
for club in standings_list:
    season = 2024
    position = int(club['team_rank'])
    team = club['team_name']
    played = int(club['games_played'])
    won = int(club['won'])
    draw = int(club['tied'])
    lost = int(club['lost'])
    goals_for = int(club['goals_scored'])
    goals_against = int(club['goals_against'])
    goals_diff = int(goals_for) - int(goals_against)

    points = int(won) * 3 + int(draw) * 1

    ## Created tuple for all the records of each team/club
    tuple_of_club_records = (season, position, team, played, won, draw, lost, goals_for, goals_against, goals_diff, points)

    ## Appending the tuple in the rows
    rows.append(tuple_of_club_records)

In [39]:
## Checking if for loop worked and all data has been successfully gathered
print(rows)

[(2024, 1, 'Liverpool', 23, 15, 6, 2, 52, 22, 30, 51), (2024, 2, 'Manchester City', 22, 15, 4, 3, 54, 25, 29, 49), (2024, 3, 'Arsenal', 23, 15, 4, 4, 47, 22, 25, 49), (2024, 4, 'Aston Villa', 23, 14, 4, 5, 49, 30, 19, 46), (2024, 5, 'Tottenham Hotspur', 23, 13, 5, 5, 49, 35, 14, 44), (2024, 6, 'Manchester United', 23, 12, 2, 9, 31, 32, -1, 38), (2024, 7, 'West Ham United', 23, 10, 6, 7, 36, 36, 0, 36), (2024, 8, 'Brighton and Hove Albion', 23, 9, 8, 6, 42, 38, 4, 35), (2024, 9, 'Newcastle United', 23, 10, 3, 10, 48, 37, 11, 33), (2024, 10, 'Wolverhampton Wanderers', 23, 9, 5, 9, 37, 37, 0, 32), (2024, 11, 'Chelsea', 23, 9, 4, 10, 38, 39, -1, 31), (2024, 12, 'Bournemouth', 22, 7, 6, 9, 30, 41, -11, 27), (2024, 13, 'Fulham', 23, 7, 5, 11, 30, 38, -8, 26), (2024, 14, 'Crystal Palace', 23, 6, 6, 11, 26, 40, -14, 24), (2024, 15, 'Brentford', 22, 6, 4, 12, 32, 39, -7, 22), (2024, 16, 'Nottingham Forest', 23, 5, 6, 12, 28, 41, -13, 21), (2024, 17, 'Luton Town', 22, 5, 5, 12, 32, 42, -10, 20), (2024, 18, 'Everton *', 23, 8, 5, 10, 26, 30, -4, 29), (2024, 19, 'Burnley', 23, 3, 4, 16, 24, 47, -23, 13), (2024, 20, 'Sheffield United', 23, 2, 4, 17, 19, 59, -40, 10)]

In [83]:
## Creating the final dataframe
df = pd.DataFrame(rows, columns=column_names)

In [84]:
## Printing the dataframe
df.head(20)

,season,position,team,played,won,draw,lost,goals_for,goals_against,goals_diff,points
0,2024,1,Liverpool,23,15,6,2,52,22,30,51
1,2024,2,Manchester City,22,15,4,3,54,25,29,49
2,2024,3,Arsenal,23,15,4,4,47,22,25,49
3,2024,4,Aston Villa,23,14,4,5,49,30,19,46
4,2024,5,Tottenham Hotspur,23,13,5,5,49,35,14,44
5,2024,6,Manchester United,23,12,2,9,31,32,-1,38
6,2024,7,West Ham United,23,10,6,7,36,36,0,36
7,2024,8,Brighton and Hove Albion,23,9,8,6,42,38,4,35
8,2024,9,Newcastle United,23,10,3,10,48,37,11,33
9,2024,10,Wolverhampton Wanderers,23,9,5,9,37,37,0,32
10,2024,11,Chelsea,23,9,4,10,38,39,-1,31
11,2024,12,Bournemouth,22,7,6,9,30,41,-11,27
12,2024,13,Fulham,23,7,5,11,30,38,-8,26
13,2024,14,Crystal Palace,23,6,6,11,26,40,-14,24
14,2024,15,Brentford,22,6,4,12,32,39,-7,22
15,2024,16,Nottingham Forest,23,5,6,12,28,41,-13,21
16,2024,17,Luton Town,22,5,5,12,32,42,-10,20
17,2024,18,Everton *,23,8,5,10,26,30,-4,29
18,2024,19,Burnley,23,3,4,16,24,47,-23,13
19,2024,20,Sheffield United,23,2,4,17,19,59,-40,10

In [85]:
## Checking the data type
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   season         20 non-null     int64
 1   position       20 non-null     int64
 2   team           20 non-null     str
 3   played         20 non-null     int64
 4   won            20 non-null     int64
 5   draw           20 non-null     int64
 6   lost           20 non-null     int64
 7   goals_for      20 non-null     int64
 8   goals_against  20 non-null     int64
 9   goals_diff     20 non-null     int64
 10  points         20 non-null     int64
dtypes: int64(10), str(1)
memory usage: 1.8 KB

## -------------------------Loading Data into Database------------------------

In [62]:
from dotenv import find_dotenv

print(find_dotenv())

c:\Users\hp\OneDrive\Desktop\Python_Tutorial_&_Projects\Football_API_Project\.env

In [63]:
import os

print(os.getcwd())

c:\Users\hp\OneDrive\Desktop\Python_Tutorial_&_Projects\Football_API_Project

In [105]:
MYSQL_HOST = os.getenv("MYSQL_HOST")
MYSQL_PORT = os.getenv("MYSQL_PORT")
MYSQL_USER = os.getenv("MYSQL_USER")
MYSQL_DATABASE = os.getenv("MYSQL_DATABASE")
MYSQL_PASSWORD = os.getenv("MYSQL_PASSWORD")

print(MYSQL_HOST)
print(MYSQL_PORT)
print(MYSQL_USER)
print(MYSQL_DATABASE)
print(MYSQL_PASSWORD)

localhost
3306
pl_app_writer
premier_league_db
7263372Sk

In [106]:
## Connecting to Database Server
server_conn = connector.connect(
    host = MYSQL_HOST,
    port = MYSQL_PORT,
    user = MYSQL_USER,
    password = MYSQL_PASSWORD,
    connection_timeout = 10,
    autocommit = False,
    raise_on_warnings = True
)

server_cur = server_conn.cursor()
print(f"[SUCCESS] - Connected to MYSQL server!")

[SUCCESS] - Connected to MYSQL server!

In [107]:
server_cur.close()
server_conn.close()

In [108]:
db_connection = connector.connect(
    host = MYSQL_HOST,
    port = MYSQL_PORT,
    user = MYSQL_USER,
    password = MYSQL_PASSWORD,
    database = MYSQL_DATABASE
)

cur = db_connection.cursor()
print(f"[SUCCESS] - Successfully connected to database!")

[SUCCESS] - Successfully connected to database!

In [109]:
sql_table = "standings"
cur.execute("SHOW TABLES LIKE %s", (f"{sql_table}",))

if cur.fetchone() is None:
    raise SystemExit(f"Table with name - {sql_table} does not exist...please create it!")
else:
    print(f"[Success] - {sql_table} exists...Continue!")

[Success] - standings exists...Continue!

In [97]:
user_team = "LIVERPOOL'; DROP TABLE standings"
cur.execute("SELECT * FROM standings WHERE team = %s", (user_team,))

In [110]:
# Starting the UPSERT Operations

table_cols = ['season', 'position', 'team', 'played', 'won', 'draw', 'lost', 'goals_for', 'goals_against', 'goals_diff', 'points']

standings_df = df[table_cols]

In [111]:
standings_df

,season,position,team,played,won,draw,lost,goals_for,goals_against,goals_diff,points
0,2024,1,Liverpool,23,15,6,2,52,22,30,51
1,2024,2,Manchester City,22,15,4,3,54,25,29,49
2,2024,3,Arsenal,23,15,4,4,47,22,25,49
3,2024,4,Aston Villa,23,14,4,5,49,30,19,46
4,2024,5,Tottenham Hotspur,23,13,5,5,49,35,14,44
5,2024,6,Manchester United,23,12,2,9,31,32,-1,38
6,2024,7,West Ham United,23,10,6,7,36,36,0,36
7,2024,8,Brighton and Hove Albion,23,9,8,6,42,38,4,35
8,2024,9,Newcastle United,23,10,3,10,48,37,11,33
9,2024,10,Wolverhampton Wanderers,23,9,5,9,37,37,0,32
10,2024,11,Chelsea,23,9,4,10,38,39,-1,31
11,2024,12,Bournemouth,22,7,6,9,30,41,-11,27
12,2024,13,Fulham,23,7,5,11,30,38,-8,26
13,2024,14,Crystal Palace,23,6,6,11,26,40,-14,24
14,2024,15,Brentford,22,6,4,12,32,39,-7,22
15,2024,16,Nottingham Forest,23,5,6,12,28,41,-13,21
16,2024,17,Luton Town,22,5,5,12,32,42,-10,20
17,2024,18,Everton *,23,8,5,10,26,30,-4,29
18,2024,19,Burnley,23,3,4,16,24,47,-23,13
19,2024,20,Sheffield United,23,2,4,17,19,59,-40,10

In [112]:
standings_records_tuples = standings_df.itertuples(index=False, name=None)

list_of_standings_records_tuples = list(standings_records_tuples)

In [113]:
UPSERT_SQL = f"""
    INSERT INTO {sql_table}
    (season, position, team, played, won, draw, lost, goals_for, goals_against, goals_diff, points)
    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) AS src
    ON DUPLICATE KEY UPDATE
    position = src.position,
    team = src.team,
    played = src.played,
    won = src.won,
    draw = src.draw,
    lost = src.lost,
    goals_for = src.goals_for,
    goals_against = src.goals_against,
    goals_diff = src.goals_diff,
    points = src.points;
"""

In [114]:
no_of_rows_uploaded_to_mysql = len(list_of_standings_records_tuples)

In [115]:
try:
    cur.executemany(UPSERT_SQL, list_of_standings_records_tuples)
    db_connection.commit()
    print(f"[Success] - UPSERT attempted for {no_of_rows_uploaded_to_mysql} rows")
except Exception as e:
    db_connection.rollback()
    print(f"[Error] - Rolled back due to this error.......: \n{e}")
finally:
    cur.close()
    db_connection.close()
    print("All databse connections now closed...\n\nClean up completed!")

[Success] - UPSERT attempted for 20 rows
All databse connections now closed...

Clean up completed!

## ------------ETL Pipeline Completed, Data successfully added to MYSQL Database------------